"""convert_snake_case_to_camelcase

Revision ID: 0847e8ca8180
Revises: 541032d4fb97
Create Date: 2025-03-18 16:17:36.254739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0847e8ca8180'
down_revision: Union[str, None] = '541032d4fb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Invoices table
    op.alter_column('invoices', 'lease_id', new_column_name='leaseId')
    op.alter_column('invoices', 'tenantId', new_column_name='tenantId')
    op.alter_column('invoices', 'apartmentId', new_column_name='apartmentId')
    op.alter_column('invoices', 'invoice_number', new_column_name='invoiceNumber')
    op.alter_column('invoices', 'issue_date', new_column_name='issueDate')
    op.alter_column('invoices', 'due_date', new_column_name='dueDate')
    op.alter_column('invoices', 'isPaid', new_column_name='isPaid')
    op.alter_column('invoices', 'payment_date', new_column_name='paymentDate')
    op.alter_column('invoices', 'payment_method', new_column_name='paymentMethod')
    op.alter_column('invoices', 'reminder_sent', new_column_name='reminderSent')
    op.alter_column('invoices', 'reminder_date', new_column_name='reminderDate')
    op.alter_column('invoices', 'createdAt', new_column_name='createdAt')
    op.alter_column('invoices', 'updatedAt', new_column_name='updatedAt')
    
    # Invoice Items table
    op.alter_column('invoice_items', 'invoice_id', new_column_name='invoiceId')
    op.alter_column('invoice_items', 'createdAt', new_column_name='createdAt')
    op.alter_column('invoice_items', 'updatedAt', new_column_name='updatedAt')
    
    # Apartments table
    op.alter_column('apartments', 'square_meters', new_column_name='squareMeters')
    op.alter_column('apartments', 'has_balcony', new_column_name='hasBalcony')
    op.alter_column('apartments', 'has_parking', new_column_name='hasParking')
    op.alter_column('apartments', 'is_furnished', new_column_name='isFurnished')
    op.alter_column('apartments', 'monthlyRent', new_column_name='monthlyRent')
    op.alter_column('apartments', 'is_available', new_column_name='isAvailable')
    op.alter_column('apartments', 'utility_meters_info', new_column_name='utilityMetersInfo')
    op.alter_column('apartments', 'createdAt', new_column_name='createdAt')
    op.alter_column('apartments', 'updatedAt', new_column_name='updatedAt')
    
    # Tenants table
    op.alter_column('tenants', 'first_name', new_column_name='firstName')
    op.alter_column('tenants', 'last_name', new_column_name='lastName')
    op.alter_column('tenants', 'document_type', new_column_name='documentType')
    op.alter_column('tenants', 'document_number', new_column_name='documentNumber')
    op.alter_column('tenants', 'document_expiry_date', new_column_name='documentExpiryDate')
    op.alter_column('tenants', 'document_front_image', new_column_name='documentFrontImage')
    op.alter_column('tenants', 'document_back_image', new_column_name='documentBackImage')
    op.alter_column('tenants', 'communication_preferences', new_column_name='communicationPreferences')
    op.alter_column('tenants', 'createdAt', new_column_name='createdAt')
    op.alter_column('tenants', 'updatedAt', new_column_name='updatedAt')
    
    # Leases table
    op.alter_column('leases', 'tenantId', new_column_name='tenantId')
    op.alter_column('leases', 'apartmentId', new_column_name='apartmentId')
    op.alter_column('leases', 'startDate', new_column_name='startDate')
    op.alter_column('leases', 'endDate', new_column_name='endDate')
    op.alter_column('leases', 'monthlyRent', new_column_name='monthlyRent')
    op.alter_column('leases', 'security_deposit', new_column_name='securityDeposit')
    op.alter_column('leases', 'is_active', new_column_name='isActive')
    op.alter_column('leases', 'payment_due_day', new_column_name='paymentDueDay')
    op.alter_column('leases', 'terms_and_conditions', new_column_name='termsAndConditions')
    op.alter_column('leases', 'special_clauses', new_column_name='specialClauses')
    op.alter_column('leases', 'createdAt', new_column_name='createdAt')
    op.alter_column('leases', 'updatedAt', new_column_name='updatedAt')
    
    # Lease Documents table
    op.alter_column('lease_documents', 'lease_id', new_column_name='leaseId')
    op.alter_column('lease_documents', 'upload_date', new_column_name='uploadDate')
    op.alter_column('lease_documents', 'createdAt', new_column_name='createdAt')
    op.alter_column('lease_documents', 'updatedAt', new_column_name='updatedAt')
    
    # Lease Payments table
    op.alter_column('lease_payments', 'lease_id', new_column_name='leaseId')
    op.alter_column('lease_payments', 'payment_date', new_column_name='paymentDate')
    op.alter_column('lease_payments', 'payment_type', new_column_name='paymentType')
    op.alter_column('lease_payments', 'createdAt', new_column_name='createdAt')
    op.alter_column('lease_payments', 'updatedAt', new_column_name='updatedAt')
    
    # Maintenance Records table
    op.alter_column('maintenance_records', 'apartmentId', new_column_name='apartmentId')
    op.alter_column('maintenance_records', 'completed_by', new_column_name='completedBy')
    op.alter_column('maintenance_records', 'createdAt', new_column_name='createdAt')
    op.alter_column('maintenance_records', 'updatedAt', new_column_name='updatedAt')
    
    # Payment Records table
    op.alter_column('payment_records', 'invoice_id', new_column_name='invoiceId')
    op.alter_column('payment_records', 'payment_date', new_column_name='paymentDate')
    op.alter_column('payment_records', 'payment_method', new_column_name='paymentMethod')
    op.alter_column('payment_records', 'createdAt', new_column_name='createdAt')
    op.alter_column('payment_records', 'updatedAt', new_column_name='updatedAt')
    
    # Utility Readings table
    op.alter_column('utility_readings', 'apartmentId', new_column_name='apartmentId')
    op.alter_column('utility_readings', 'readingDate', new_column_name='readingDate')
    op.alter_column('utility_readings', 'previousReading', new_column_name='previousReading')
    op.alter_column('utility_readings', 'currentReading', new_column_name='currentReading')
    op.alter_column('utility_readings', 'unitCost', new_column_name='unitCost')
    op.alter_column('utility_readings', 'totalCost', new_column_name='totalCost')
    op.alter_column('utility_readings', 'isPaid', new_column_name='isPaid')
    op.alter_column('utility_readings', 'paidDate', new_column_name='paidDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Invoices table
    op.alter_column('invoices', 'leaseId', new_column_name='lease_id')
    op.alter_column('invoices', 'tenantId', new_column_name='tenantId')
    op.alter_column('invoices', 'apartmentId', new_column_name='apartmentId')
    op.alter_column('invoices', 'invoiceNumber', new_column_name='invoice_number')
    op.alter_column('invoices', 'issueDate', new_column_name='issue_date')
    op.alter_column('invoices', 'dueDate', new_column_name='due_date')
    op.alter_column('invoices', 'isPaid', new_column_name='isPaid')
    op.alter_column('invoices', 'paymentDate', new_column_name='payment_date')
    op.alter_column('invoices', 'paymentMethod', new_column_name='payment_method')
    op.alter_column('invoices', 'reminderSent', new_column_name='reminder_sent')
    op.alter_column('invoices', 'reminderDate', new_column_name='reminder_date')
    op.alter_column('invoices', 'createdAt', new_column_name='createdAt')
    op.alter_column('invoices', 'updatedAt', new_column_name='updatedAt')
    
    # Invoice Items table
    op.alter_column('invoice_items', 'invoiceId', new_column_name='invoice_id')
    op.alter_column('invoice_items', 'createdAt', new_column_name='createdAt')
    op.alter_column('invoice_items', 'updatedAt', new_column_name='updatedAt')
    
    # Apartments table
    op.alter_column('apartments', 'squareMeters', new_column_name='square_meters')
    op.alter_column('apartments', 'hasBalcony', new_column_name='has_balcony')
    op.alter_column('apartments', 'hasParking', new_column_name='has_parking')
    op.alter_column('apartments', 'isFurnished', new_column_name='is_furnished')
    op.alter_column('apartments', 'monthlyRent', new_column_name='monthlyRent')
    op.alter_column('apartments', 'isAvailable', new_column_name='is_available')
    op.alter_column('apartments', 'utilityMeters_info', new_column_name='utility_meters_info')
    op.alter_column('apartments', 'createdAt', new_column_name='createdAt')
    op.alter_column('apartments', 'updatedAt', new_column_name='updatedAt')
    
    # Tenants table
    op.alter_column('tenants', 'firstName', new_column_name='first_name')
    op.alter_column('tenants', 'lastName', new_column_name='last_name')
    op.alter_column('tenants', 'documentType', new_column_name='document_type')
    op.alter_column('tenants', 'documentNumber', new_column_name='document_number')
    op.alter_column('tenants', 'documentExpiryDate', new_column_name='document_expiry_date')
    op.alter_column('tenants', 'documentFrontImage', new_column_name='document_front_image')
    op.alter_column('tenants', 'documentBackImage', new_column_name='document_back_image')
    op.alter_column('tenants', 'communicationPreferences', new_column_name='communication_preferences')
    op.alter_column('tenants', 'createdAt', new_column_name='createdAt')
    op.alter_column('tenants', 'updatedAt', new_column_name='updatedAt')
    
    # Leases table
    op.alter_column('leases', 'tenantId', new_column_name='tenantId')
    op.alter_column('leases', 'apartmentId', new_column_name='apartmentId')
    op.alter_column('leases', 'startDate', new_column_name='startDate')
    op.alter_column('leases', 'endDate', new_column_name='endDate')
    op.alter_column('leases', 'monthlyRent', new_column_name='monthlyRent')
    op.alter_column('leases', 'securityDeposit', new_column_name='security_deposit')
    op.alter_column('leases', 'isActive', new_column_name='is_active')
    op.alter_column('leases', 'paymentDueDay', new_column_name='payment_due_day')
    op.alter_column('leases', 'termsAndConditions', new_column_name='terms_and_conditions')
    op.alter_column('leases', 'specialClauses', new_column_name='special_clauses')
    op.alter_column('leases', 'createdAt', new_column_name='createdAt')
    op.alter_column('leases', 'updatedAt', new_column_name='updatedAt')
    
    # Lease Documents table
    op.alter_column('lease_documents', 'leaseId', new_column_name='lease_id')
    op.alter_column('lease_documents', 'uploadDate', new_column_name='upload_date')
    op.alter_column('lease_documents', 'createdAt', new_column_name='createdAt')
    op.alter_column('lease_documents', 'updatedAt', new_column_name='updatedAt')
    
    # Lease Payments table
    op.alter_column('lease_payments', 'leaseId', new_column_name='lease_id')
    op.alter_column('lease_payments', 'paymentDate', new_column_name='payment_date')
    op.alter_column('lease_payments', 'paymentType', new_column_name='payment_type')
    op.alter_column('lease_payments', 'createdAt', new_column_name='createdAt')
    op.alter_column('lease_payments', 'updatedAt', new_column_name='updatedAt')
    
    # Maintenance Records table
    op.alter_column('maintenance_records', 'apartmentId', new_column_name='apartmentId')
    op.alter_column('maintenance_records', 'completedBy', new_column_name='completed_by')
    op.alter_column('maintenance_records', 'createdAt', new_column_name='createdAt')
    op.alter_column('maintenance_records', 'updatedAt', new_column_name='updatedAt')
    
    # Payment Records table
    op.alter_column('payment_records', 'invoiceId', new_column_name='invoice_id')
    op.alter_column('payment_records', 'paymentDate', new_column_name='payment_date')
    op.alter_column('payment_records', 'paymentMethod', new_column_name='payment_method')
    op.alter_column('payment_records', 'createdAt', new_column_name='createdAt')
    op.alter_column('payment_records', 'updatedAt', new_column_name='updatedAt')
    
    # Utility Readings table
    op.alter_column('utility_readings', 'apartmentId', new_column_name='apartmentId')
    op.alter_column('utility_readings', 'readingDate', new_column_name='readingDate')
    op.alter_column('utility_readings', 'previousReading', new_column_name='previousReading')
    op.alter_column('utility_readings', 'currentReading', new_column_name='currentReading')
    op.alter_column('utility_readings', 'unitCost', new_column_name='unitCost')
    op.alter_column('utility_readings', 'totalCost', new_column_name='totalCost')
    op.alter_column('utility_readings', 'isPaid', new_column_name='isPaid')
    op.alter_column('utility_readings', 'paidDate', new_column_name='paidDate')
    op.alter_column('invoices', 'reminderDate', new_column_name='reminder_date')
    # ### end Alembic commands ###
