"""Initial migration

Revision ID: 5e8367871dc4
Revises: 
Create Date: 2025-03-18 00:14:26.674840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8367871dc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('squareMeters', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('hasBalcony', sa.Boolean(), nullable=True),
    sa.Column('hasParking', sa.Boolean(), nullable=True),
    sa.Column('isFurnished', sa.Boolean(), nullable=True),
    sa.Column('monthlyRent', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('isAvailable', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('utilityMetersInfo', sa.JSON(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartments_id'), 'apartments', ['id'], unique=False)
    op.create_index(op.f('ix_apartments_name'), 'apartments', ['name'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('documentType', sa.String(), nullable=True),
    sa.Column('documentNumber', sa.String(), nullable=True),
    sa.Column('documentExpiryDate', sa.Date(), nullable=True),
    sa.Column('documentFrontImage', sa.String(), nullable=True),
    sa.Column('documentBackImage', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('communicationPreferences', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenantId', sa.Integer(), nullable=True),
    sa.Column('apartmentId', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('monthlyRent', sa.Float(), nullable=True),
    sa.Column('securityDeposit', sa.Float(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('paymentDueDay', sa.Integer(), nullable=True),
    sa.Column('termsAndConditions', sa.Text(), nullable=True),
    sa.Column('specialClauses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apartmentId'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['tenantId'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_id'), 'leases', ['id'], unique=False)
    op.create_table('maintenanceRecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartmentId', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('completedBy', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apartmentId'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leaseId', sa.Integer(), nullable=True),
    sa.Column('tenantId', sa.Integer(), nullable=True),
    sa.Column('apartmentId', sa.Integer(), nullable=True),
    sa.Column('invoiceNumber', sa.String(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('issueDate', sa.Date(), nullable=True),
    sa.Column('dueDate', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('isPaid', sa.Boolean(), nullable=True),
    sa.Column('paymentDate', sa.Date(), nullable=True),
    sa.Column('paymentMethod', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminderSent', sa.Boolean(), nullable=True),
    sa.Column('reminderDate', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apartmentId'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['leaseId'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['tenantId'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_table('leaseDocuments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leaseId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('uploadDate', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leaseId'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lease_documents_id'), 'lease_documents', ['id'], unique=False)
    op.create_table('leasePayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leaseId', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('paymentDate', sa.Date(), nullable=True),
    sa.Column('paymentType', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leaseId'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lease_payments_id'), 'lease_payments', ['id'], unique=False)
    op.create_table('invoiceItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoiceId', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_table('paymentRecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoiceId', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('paymentDate', sa.Date(), nullable=True),
    sa.Column('paymentMethod', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_id'), 'payment_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_records_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_lease_payments_id'), table_name='lease_payments')
    op.drop_table('lease_payments')
    op.drop_index(op.f('ix_lease_documents_id'), table_name='lease_documents')
    op.drop_table('lease_documents')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_leases_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_apartments_name'), table_name='apartments')
    op.drop_index(op.f('ix_apartments_id'), table_name='apartments')
    op.drop_table('apartments')
    # ### end Alembic commands ###
