"""Add password reset tokens table

Revision ID: 82b4088122eb
Revises: 06e396ab912e
Create Date: 2025-04-15 13:53:58.809814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82b4088122eb'
down_revision: Union[str, None] = '06e396ab912e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('refresh_tokens', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('refresh_tokens', 'expires',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('refresh_tokens_token_key', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashedPassword',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashedPassword',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_token_key', 'refresh_tokens', ['token'])
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refresh_tokens', 'expires',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refresh_tokens', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
