"""convert_snake_case_to_camelcase

Revision ID: cb3ebfb537ce
Revises: 0847e8ca8180
Create Date: 2025-03-18 17:29:58.287979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb3ebfb537ce'
down_revision: Union[str, None] = '0847e8ca8180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('utilityMetersInfo', sa.JSON(), nullable=True))
    op.drop_column('apartments', 'utilityMeters_info')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.create_index(op.f('ix_invoices_invoiceNumber'), 'invoices', ['invoiceNumber'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoiceNumber'), table_name='invoices')
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoiceNumber'], unique=False)
    op.add_column('apartments', sa.Column('utilityMeters_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('apartments', 'utilityMetersInfo')
    # ### end Alembic commands ###
